DROP TABLE CUSTOMERS;

CREATE TABLE CUSTOMERS
(CUST_ID NUMERIC (5),
CUST_NAME CHAR (20) NOT NULL,
CUST_PHONE NUMERIC (10),
CUST_EMAIL VARCHAR2(10));

DROP TABLE DOGS;

CREATE TABLE DOGS
(DOG_ID NUMERIC(5),
DOG_NAME CHAR(10),
DOG_BREED CHAR (25),
DOG_MEDCOND CHAR (35),
DOG_GENDER CHAR(1));

DROP TABLE KENNELS;

CREATE TABLE KENNELS
(KENNEL_ID NUMERIC(5),
KENNEL_TYPE CHAR(5),
KENNEL_STATUS CHAR (10));

DROP TABLE RESERVATIONS;

CREATE TABLE RESERVATIONS
(RES_ID NUMERIC(5),
KENNEL_ID NUMERIC(5),
DOG_ID NUMERIC(5),
RES_COST NUMERIC (20),
RES_STATUS CHAR(5));

COMMIT;